#!/bin/bash

# Leer AUTH
if [ -f "/root/auth" ]; then
    IFS=$'\n' read -d '' -r -a lines < "/root/auth"
    if [ "${#lines[@]}" -ge 2 ]; then
        BOT_TOKEN="${lines[0]}"
        CHAT_ID="${lines[1]}"
    else
        echo "El archivo de autenticación debe tener al menos 2 líneas (su token y su ID de chat)."
        exit 1
    fi
else
    echo "Archivo de autenticación no encontrado."
    exit 1
fi

# Función para enviar mensajes a los bots de Telegram
send_telegram_message() {
    chat_id="$1"
    message="$2"
    curl -s -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" -d "chat_id=$chat_id&text=$message" > /dev/null
}

# Función para recolectar datos de vnstat (en algunos casos necesario cambiar la interfaz de red, se consulta usando ip -a)
get_daily_bandwidth() {

# Función para leer y enviar el archivo /etc/SSHPlus/RegV2ray
send_regv2ray_file() {
    if [ -f "/etc/SSHPlus/RegV2ray" ]; then
        regv2ray_content=$(cat "/etc/SSHPlus/RegV2ray")
        send_telegram_message "$CHAT_ID" "$regv2ray_content"
    else
        echo "Archivo /etc/SSHPlus/RegV2ray no encontrado."
        exit 1
    fi
}

# Enviar mensajes a cuentas personales de Telegram
send_telegram_message "$CHAT_ID" "$bandwidth_message"

# Enviar el archivo /etc/SSHPlus/RegV2ray
send_regv2ray_file

# Recibir mensaje desde bot
if [[ "$message" == "regv2ray" ]]; then 
    send_telegram_message "$CHAT_ID" "$(get_daily_bandwidth)"; 
fi
